-- Stage 6 durable final shared Reverse isolation.  Each court has real state;
-- Court 1's retained history is reversed while Court 2's full semantic state
-- and its independent history/reversal identity remain unchanged.
begin;
do $$
declare
 fid uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); u2 uuid:=gen_random_uuid(); a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); d uuid:=gen_random_uuid(); x uuid:=gen_random_uuid(); y uuid:=gen_random_uuid();
 t1 uuid:=gen_random_uuid(); t2 uuid:=gen_random_uuid(); q1 uuid:=gen_random_uuid(); q2 uuid:=gen_random_uuid(); g1 uuid; g2 uuid; r jsonb; c2_before jsonb;
begin
 insert into public.facilities(id,name,slug,code) values(fid,'S6 multicourt reverse','s6-mc-'||left(fid::text,8),left(fid::text,8));
 insert into auth.users(id,instance_id,aud,role,email) values(u,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',u||'@test'),(u2,'00000000-0000-0000-0000-000000000000','authenticated','authenticated',u2||'@test');
 insert into public.user_facility_sessions(user_id,facility_id) values(u,fid),(u2,fid); insert into public.facility_admin_credentials(facility_id,username,display_username,password_hash) values(fid,'admin','Admin',crypt('x',gen_salt('bf'))); insert into public.admin_sessions(user_id,username,facility_id) values(u,'admin',fid); perform set_config('request.jwt.claim.sub',u::text,true);
 insert into public.waitlist_config(facility_id,id,game_number,max_players,mode,court_count,geofence_enabled,hybrid_rotation_rule) values(fid,true,1,24,'hybrid_waitlist',2,false,'kotc');
 insert into public.waitlist_courts(facility_id,court_number,game_number,team_mode) values(fid,1,1,'king'),(fid,2,1,'king'); insert into public.daily_waitlist_reset_state(facility_id,id) values(fid,true); insert into public.hybrid_kotc_court_state(facility_id,court_number,version,initialized_game_number) values(fid,1,10,1),(fid,2,20,1);
 insert into public.waitlist_players(id,facility_id,user_id,first_name,last_name,display_name,status,queue_position,court_number) values(a,fid,u,'A','','A','current',1,1),(b,fid,null,'B','','B','current',2,1),(c,fid,null,'C','','C','current',3,1),(d,fid,null,'D','','D','current',4,1),(x,fid,u2,'X','','X','current',5,2),(y,fid,null,'Y','','Y','current',6,2);
 insert into public.waitlist_players(id,facility_id,first_name,last_name,display_name,status,queue_position) select gen_random_uuid(),fid,'Q'||n,'','Q'||n,'waiting',20+n from generate_series(1,12)n;
 insert into public.hybrid_kotc_teams(id,facility_id,court_number,court_side,appearance_game_number,status) values(t1,fid,1,1,1,'current'),(t2,fid,1,2,1,'current'),(q1,fid,2,1,1,'current'),(q2,fid,2,2,1,'current');
 insert into public.hybrid_kotc_slots(facility_id,team_id,slot_number,player_id) values(fid,t1,1,a),(fid,t1,2,b),(fid,t1,3,null),(fid,t1,4,null),(fid,t1,5,null),(fid,t1,6,null),(fid,t2,1,c),(fid,t2,2,d),(fid,t2,3,null),(fid,t2,4,null),(fid,t2,5,null),(fid,t2,6,null),(fid,q1,1,x),(fid,q1,2,null),(fid,q1,3,null),(fid,q1,4,null),(fid,q1,5,null),(fid,q1,6,null),(fid,q2,1,y),(fid,q2,2,null),(fid,q2,3,null),(fid,q2,4,null),(fid,q2,5,null),(fid,q2,6,null);
 r:=public.advance_hybrid_kotc_game(1,'win',fid,1,10); perform set_config('request.jwt.claim.sub',u2::text,true); r:=public.advance_hybrid_kotc_game(2,'win',fid,1,20); perform set_config('request.jwt.claim.sub',u::text,true);
 select r.game_id into strict g1 from public.court_game_reversals r join public.past_games p on p.id=r.game_id where r.facility_id=fid and p.court_number=1; select r.game_id into strict g2 from public.court_game_reversals r join public.past_games p on p.id=r.game_id where r.facility_id=fid and p.court_number=2;
 select jsonb_build_object('teams',(select jsonb_agg(jsonb_build_object('id',id,'side',court_side,'status',status,'wins',consecutive_wins) order by id) from public.hybrid_kotc_teams where facility_id=fid and court_number=2),'slots',(select jsonb_agg(jsonb_build_object('team',team_id,'slot',slot_number,'player',player_id) order by team_id,slot_number) from public.hybrid_kotc_slots where facility_id=fid and team_id in(select id from public.hybrid_kotc_teams where facility_id=fid and court_number=2)),'v',(select version from public.hybrid_kotc_court_state where facility_id=fid and court_number=2),'history',g2,'reversal',(select game_id from public.court_game_reversals where game_id=g2)) into c2_before;
 perform public.reverse_past_game_guarded(g1,fid);
 if exists(select 1 from public.past_games where id=g1) or not exists(select 1 from public.past_games where id=g2) or not exists(select 1 from public.court_game_reversals where game_id=g2) or c2_before is distinct from jsonb_build_object('teams',(select jsonb_agg(jsonb_build_object('id',id,'side',court_side,'status',status,'wins',consecutive_wins) order by id) from public.hybrid_kotc_teams where facility_id=fid and court_number=2),'slots',(select jsonb_agg(jsonb_build_object('team',team_id,'slot',slot_number,'player',player_id) order by team_id,slot_number) from public.hybrid_kotc_slots where facility_id=fid and team_id in(select id from public.hybrid_kotc_teams where facility_id=fid and court_number=2)),'v',(select version from public.hybrid_kotc_court_state where facility_id=fid and court_number=2),'history',g2,'reversal',(select game_id from public.court_game_reversals where game_id=g2)) then raise exception 'Court 1 Reverse crossed Court 2 semantic/history boundary'; end if;
 raise notice 'final multicourt exact Reverse isolation PASS';
end $$;
rollback;
